### ISSUE TITLE
Ophalen video uit 2008 geeft UTF-8 fout

### ISSUE THREAD

**Issue by mwesten** [Carpetsmoker/download-npo#10]
Hoi, wanneer ik `TELEA_1033559` probeer binnen te halen, krijg ik een UTF-8 error. Waarschijnlijk wordt daar nog gewoon gebruik gemaakt van een latin1 encoding en gaat ie daarom onderuit?

`download-npo -VVV TELEA_1033559` geeft (alleen laatste stukje van log):
```
OpenUrl url: http://content.omroep.nl/id/TELEAC_NOT/serie/TELEA_1027126/TELEA_1033559/bb.20080411.mp4
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/download-npo", line 308, in <module>
    options['metaonly'], options['getsubs'], options['quality'])
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/download-npo", line 176, in Download
    videourl, playerId, ext = site.FindVideo(v, quality)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/download_npo/sites.py", line 206, in FindVideo
    stream = self.GetJSON(stream['url'])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/download_npo/sites.py", line 80, in GetJSON
    data = re.sub(r'^[\w\d\?]+\(', r'',  self.GetPage(url))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/download_npo/sites.py", line 73, in GetPage
    if sys.version_info[0] > 2: data = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 63: invalid continuation byte
```

**Comment by mwesten** [comment]
Bij nader inzien: Kan het nu niet meer reproduceren....  Was duidelijk te snel met het posten van het issue..... Sorry daarvoor!

**Comment by arp242** [comment]
Ik had het vanochtend ook, en ook nu werkt het niet voor me?

**Comment by arp242** [comment]
Okay, dit zou nu gefixed moeten zijn. Probleem was dat normaal gesproken je eerst eerst JSON bestand moet ophalen en daar dan het mp4 betstand uit moet halen. Echter, in dit geval was het *meteen* een mp4 videobestand. Dat is natuurlijk geen geldig utf-8.

> Bij nader inzien: Kan het nu niet meer reproduceren

Dat is apart; snap niet helemaal hoe je dit werkend hebt gekregen met deze URL?

**Comment by mwesten** [comment]
Er ging hier het een en ander al niet helemaal lekker met m'n dev-omgeving (gebruikte mixed versies van python (libs van v3 en v2 binary(net systeem opnieuw opgebouwd, zonder dat ik dat al had ingericht).
Volgens mij zou de fix in https://github.com/mwesten/download-npo/commit/4ac64d8fd2333769c6eb1865be537402d6a11dfc dit ook al ondervangen moeten hebben.
