### ISSUE TITLE
pip install always gives me 2.5.5

### ISSUE THREAD

**Issue by ghost** [Carpetsmoker/download-npo#11]
Hi,

I'm not very familiar how pip works, but I try to get the latest version:

```
$ sudo pip install download-npo --upgrade
Requirement already up-to-date: download-npo in /usr/local/lib/python2.7/dist-packages
```
tried un-install:
```
$ sudo pip uninstall download-npo
Uninstalling download-npo-2.5.5:
<blabla>
Successfully uninstalled download-npo-2.5.5
```
and re-install:
```
$ pip install download-npc
Collecting download-npo
Installing collected packages: download-npo
Successfully installed download-npo-2.5.5
```
I think I really need 2.5.5+ because the url of the player returns 404 🙃

Right now I'm stuck, don't know how to get to the newer versions, the PPA doesn't work either:

```
$ sudo apt-get update
<blabla>
W: Failed to fetch http://ppa.launchpad.net/maarten-fonville/download-npo/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found
```

Can you help me?

**Comment by ghost** [comment]
OOpz.. just read the README it isn't maintained anymore.

`./setyp.py install` worked of me 👍

**Comment by arp242** [comment]
> OOpz.. just read the README it isn't maintained anymore.

Wat is niet meer ondersteund? `pip` zou gewoon moeten werken:

```
[~]% pip install download-npo
Collecting download-npo
  Downloading download_npo-2.7-py3-none-any.whl
Installing collected packages: download-npo
Successfully installed download-npo-2.7

[~]% download-npo -v
download-npo 2.7, 2017-03-19
http://code.arp242.net/download-npo
```

Ik zie wel dat de python 2 versie inderdaad altijd 2.5.5 pakt om de een of andere reden:

```
[~]% sudo pip2 install download-npo
Collecting download-npo
  Using cached download-npo-2.5.5.tar.gz
Installing collected packages: download-npo
  Running setup.py install for download-npo ... done
Successfully installed download-npo-2.5.5
```

Altijd gedoe, met Python 2 :-/ Zal ik straks even naar kijken.

De apt-get packages weet ik niet zo, dat doe ik namelijk niet zelf, maar wordt door @mfonville gedaan.

**Comment by ghost** [comment]
hehe.

Ik dacht dat de opmerking op de README over de pip-installer ging, beetje onduidelijk ;)

anyway, hij doet het (voor mij) in ieder geval weer, heel blij!

**Comment by arp242** [comment]
> Ik dacht dat de opmerking op de README over de pip-installer ging, beetje onduidelijk ;)

Welke opmerking?

**Comment by ghost** [comment]
`De automatische installer is al een tijd niet meer bijgewerkt. Voel je vrij om je te melden mocht je interesse hebben om hier aan te werken.`

Dacht dit dat een 'algemene' opmerking was.

**Comment by arp242** [comment]
Oh, nee, dat geld alleen voor Windows. Ik had eerst installers voor, maar dat was altijd gedoe met vage errors. Dat is al een hele tijd kapot, dus voegt niet zo veel meer toe. Zal die opmerking weghalen.

Dank voor het melden.

**Comment by arp242** [comment]
Gefixed met:

    ./setup.py sdist upload
    python2 setup.py bdist_egg upload

Volgens mij is dat tweede command niet nodig trouwens.

```
[~]# pip2 install download-npo
Collecting download-npo
  Downloading download-npo-2.7.tar.gz
Installing collected packages: download-npo
  Running setup.py install for download-npo ... done
Successfully installed download-npo-2.7
```

**Comment by arp242** [comment]
De Ubuntu packages worden zo te zien niet voor "jessie" gemaakt:

http://ppa.launchpad.net/maarten-fonville/download-npo/ubuntu/dists/

Alleen "xenial", "yakkety", en "zesty".

**Comment by ghost** [comment]
upgraden doet het ook weer yeay!

```
$ sudo pip install download-npo --upgrade
Collecting download-npo
  Downloading download-npo-2.7.tar.gz
Building wheels for collected packages: download-npo
  Running setup.py bdist_wheel for download-npo ... done
  Stored in directory: /root/.cache/pip/wheels/38/6d/fc/f33179c90d524bb0f1f52b85c2fb5015e2ac26323356096a77
Successfully built download-npo
Installing collected packages: download-npo
  Found existing installation: download-npo 2.5.5
    Uninstalling download-npo-2.5.5:
      Successfully uninstalled download-npo-2.5.5
Successfully installed download-npo-2.7
```

Thanks!
