### ISSUE TITLE
BUG Installing with pip does not work

### ISSUE THREAD

**Issue by N00bDaan** [Carpetsmoker/download-npo#12]
```
$ pip install download-npo
Collecting download-npo
  Downloading download_npo-2.7-py3-none-any.whl
Installing collected packages: download-npo
Successfully installed download-npo-2.7

$ download-npo
Traceback (most recent call last):
  File "/var/lib/flexget/flexgetvenv/bin/download-npo", line 4, in <module>
    import download_npo.cli
ModuleNotFoundError: No module named 'download_npo'
```

Cloning the git does work as the folder download_npo and file cli.py are found..

**Comment by arp242** [comment]
`/var/lib/flexget/flexgetvenv/bin/download-npo` is een apart pad. Ik denk dat het de "verkeerde" versie pakt, ofzo? Normaal gesproken zou dit in `/usr/bin/download-npo` (of `/usr/local/bin/download-npo`) staan.

Hoe dan ook, versie 2.7 van `pip` lijkt te werken voor mij...

**Comment by arp242** [comment]
Lijkt een probleem met de omgeving te zijn. Het programma installeert een Python package `download_npo` in (normaal gesproken) `/usr/lib/python<versie>/site_packages/` en een simpel script die dat package gebruikt in `/usr/bin/`.

In jouw geval is dat script wel geïnstalleerd (in `/var/lib/flexget/flexgetvenv/bin/`, wat een apart pad is), maar kan het de Python package niet vinden om de een of andere reden.

Wellicht dat dit geïnstalleerd is in `/var/lib/flexget/flexgetvenv/lib/python<versie>` of iets dergelijks?

Of misschien dat `PYTHONHOME` or `PYTHONPATH` niet goed ingesteld staan?

Ik heb wat meer informatie nodig over je omgeving om hier echt een antwoord op te kunnen geven ben ik bang.

**Comment by arp242** [comment]
Gesloten wegens gebrek aan feedback.
