### ISSUE TITLE
can't download keuringsdienst van waarde

### ISSUE THREAD

**Issue by mfonville** [Carpetsmoker/download-npo#14]
NPO.nl probably changed their site again, since May 18th I get when trying to download episodes from Keuringsdienst van Waarde:
```
download-npo -t http://www.npo.nl/keuringsdienst-van-waarde/19-05-2017/KN_1691171
error: De URL http://ida.omroep.nl/app.php/KN_1691171?adaptive=no&token=20blu9rl7t942jopjkcljobup7 is niet gevonden (404 error)
```

**Comment by mfonville** [comment]
Oh sorry, it seems the episode is not available by npo.nl, and that is probably the cause.

**Comment by arp242** [comment]
In de URL staat: "19-05-2017". Ik denk dat dit de aflevering van vandaag is?

Soms staan afleveringen al eerder op de site maar kan je ze niet bekijken (vraag me niet waarom). Vanavond of morgen nog eens proberen en dan werkt het waarschijnlijk wel.

**Comment by mfonville** [comment]
yes, dat lijkt het probleem. Aparte workflow hebben ze daar X-D
