### ISSUE TITLE
compleet seizoen downloaden

### ISSUE THREAD

**Issue by arp242** [Carpetsmoker/download-npo#2]
Was Bitbucket issue 10:

> Is het mogelijk een compleet seizoen van een bepaald programma te downloaden? Wat ik nu doe is alle URLs van afleveringen los invoeren, kost aardig wat tijd voor sommige programma's. Dat moet vast sneller kunnen toch?

**Comment by arp242** [comment]
Ik had daar vroeger een tooltje voor, maar dit ging om de paar weken kapot dus ben ik maar mee opgehouden... Dit staat ook in de FAQ trouwens:

> Kan ik ook in 1 keer alle uitzendingen downloaden van een bepaald programma?
> Niet direct. Eerst kon dat wel, maar dat ging te vaak kapot omdat de site veranderd werd.
> Voor Windows is er de Npo-Pvr PowerShell wrapper door Jan Hoek. Door periodiek dit scriptje te starten worden steeds de nieuwste afleveringen gedownload.

Misschien dat ik daar ooit nog eens iets maak (dat Npo-Pvr ding blijkt vrij stabiel te zijn, dus zo te zien wordt er tegenwoordig minder veranderd) maar dit heeft op het moment geen prioriteit...

**Comment by mfonville** [comment]
Kijkend naar de [flexget code](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/input/npo_watchlist.py#L222) zou dit niet heel moeilijk (meer) hoeven te zijn; 

Vraag een series pagina op met `search?category=broadcasts` [zoals voor de dijken breken](http://www.npo.nl/als-de-dijken-breken/VPWON_1261083/search?category=broadcasts).
Daarna iteraten over alle `<a href>`-entries voor de episodes.
Vraag is vooral of het wel tot de scope van de tool behoort...

**Comment by arp242** [comment]
In de `list` branch zit was Work-In-Progress spul. Zal proberen dat dit weekend af te maken!

**Comment by arp242** [comment]
Zit nu in master. Het is niet echt "af", maar het werkt.

**Comment by arp242** [comment]
Zit erin vanaf 2.7.
