### ISSUE TITLE
Voeg toe aan lijst - gui hangt/doet niets

### ISSUE THREAD

**Issue by bioluminesceme** [Carpetsmoker/download-npo#21]
## GUI

Alles geïnstalleerd, download-npo-gui.pyw opent de GUI. 
ID ingevuld, maar "toevoegen aan lijst" doet niets en GUI hangt nadat ik daar op geklikt heb 
met "Not responding" in de balk bovenaan.

Windows 10 met zowel python 2.7 als python 3 geïnstalleerd, 

## Command line.

download-npo werkt prima op mijn mac mini via command line, dus mijn andere optie was om hetzelfde op windows te proberen. 

    > pip3 install download-npo 

download-npo wordt met succes geïnstalleerd, maar daarna loop ik vast.

    > download-npo ID 
    
-> scherm van Windows dat vraagt hoe ik iets openen wil. (als ik SublimeText kies opent hij een klein bestand met  import download_npo.cli download_npo.cli.main() )
    
    > py -3 download-npo ID 
    
doet niets

download-npo folder aan windows PATH toevoegen helpt ook niet.

**Comment by arp242** [comment]
Welke URL/ID gebruik je?

**Comment by bioluminesceme** [comment]
3 afleveringen Wie is de mol

AT_2111641
AT_2111642
AT_2111643

**Comment by arp242** [comment]
Het lijkt op mijn Linux computer goed te werken, met Python 3.7. Als ik die IDs plak, "voeg toe aan lijst" klik, en dan "start alles" klik begint het met downloaden. Ik heb geen Windows computer om het daar op te testen.

Als de commandline tools goed werken is het waarschijnlijk een probleem in de GUI logica. Om heel eerlijk te zijn heb ik niet zo heel interesse om daar zelf naar te kijken; ik gebruik download-npo überhaupt zeer weinig, en nooit de GUI. Ik heb ook een hele hoop andere projecten waar ik veel meer interesse in heb. Sorry :-(

Ik test en merge natuurlijk graag patches om het probleem op te lossen, of help je als je vragen hebt. Maar ik ben bang dat je voor het grootste deel zelf moet zal moeten kijken of je het probleem kan oplossen (["DIY ethic"](https://arp242.net/weblog/diy.html)).

**Comment by bioluminesceme** [comment]
Ah,  heb de command line nu werkend op windows. 
Niet via pip install download-npo, maar door de download-npo in de github Zip te gebruiken.
(na > pip install mutagen werkt alles net als op mac).

    > (downloadmap/download-npo-version-2.9.1)> python download-npo ID

Zal kijken of ik de GUI kan debuggen, maar weet niet of mijn python kennis daar goed genoeg voor is.

**Comment by arp242** [comment]
> Niet via pip install download-npo, maar door de download-npo in de github Zip te gebruiken. (na > pip install mutagen werkt alles net als op mac).

Hm, apart. Installatie op Windows is altijd al een gedoe geweest. Ik maakte vroeger .exe bestanden om dat makkelijker te maken, maar dat was altijd een gedoe en op een gegeven moment ging het kapot en kreeg ik het niet meer aan de praat. Zie ook #1, waar ik blijkbaar ook moeite had met pip, maar AppVeyor maakt nu installers (zie laatste comment). Je zou dat kunnen proberen, en als het werkt kan ik de installatie instructies aanpassen: https://ci.appveyor.com/project/Carpetsmoker/download-npo/branch/master/job/wf1vb528941c8bvh/artifacts
