### ISSUE TITLE
download-npo v2.5.2 - error  URL http://ida.omroep.nl/npoplayer/i.js is niet gevonden (404 error)

### ISSUE THREAD

**Issue by djkwee20** [Carpetsmoker/download-npo#9]
Use download-npo  version 2.5.2 to download http://www.npo.nl/dream-school/01-03-2017/VPWON_1265441 - get error De URL **http://ida.omroep.nl/npoplayer/i.js** is niet gevonden (404 error).

http://ida.omroep.nl/npoplayer/i.js
Gone
The requested resource /npoplayer/i.js
is no longer available on this server and there is no forwarding address. Please remove all references to this resource.

**Comment by arp242** [comment]
Er was het eea. veranderd op de site. Met 2.6 zou dit nu gefixed moeten zijn. Ik heb het niet heel uitvoerig getest, aangezien ik ook op werk ben :-) Laat me weten als je nog problemen hebt!

Dank voor het melden.

**Comment by mfonville** [comment]
Is het trouwens een idee om bijvoorbeeld iedere donderdag op vrijdagnacht een aantal voorgeprogrammeerde URLs op te halen met bijvoorbeeld een travis-job, om te kijken of de site verandert is?
Want we weten inmiddels dat NPO.nl updates lanceert (laat) op de donderdagavond, dus als er automatisch snapshots gemaakt worden, zou het makkelijk zijn om eventuele wijzigingen die impact zouden kunnen hebben op download-npo (en ook op de flexget plugin) makkelijk in de gaten te houden.

@Carpetsmoker wat zijn jouw gedachten?

**Comment by arp242** [comment]
Als het goed is zou de Travis job al elke dag moeten draaien @mfonville : 
https://travis-ci.org/Carpetsmoker/download-npo

Ik kan het niet vaker dan 1x per dag doen. Ook een bepaalde tijd instellen lijkt niet te kunnen(?) In dit geval was de bug report sneller dan de Travis job :-)
